name: ajanda_uygulama
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP istekleri için
  http: ^1.2.0
  # Tarih formatlama
  intl: ^0.20.2
  # Veri saklama (Oturum vb.)
  shared_preferences: ^2.2.2
  
  # İkonlar
  cupertino_icons: ^1.0.6
  # İzin yönetimi
  permission_handler: ^12.0.1
  # Tanıtım ekranı
  introduction_screen: ^4.0.0
  # Grafikler
  fl_chart: ^1.1.1
  # Konfetiler
  confetti: ^0.8.0
  table_calendar: ^3.0.9  # Takvim için
  google_nav_bar: ^5.0.6
  flutter_markdown: ^0.7.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true